# Generated by Django 4.2 on 2025-04-21 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('Aadhaar', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('VoterID', 'Voter ID'), ('RationCard', 'Ration Card'), ('Birth Certificate', 'Birth Certificate'), ('Marriage Certificate', 'Marriage Certificate'), ('Passport', 'Passport'), ('Death Certificate', 'Death Certificate')], max_length=20)),
                ('id_proof', models.FileField(upload_to='id_proofs/')),
                ('address_proof', models.FileField(upload_to='address_proofs/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
