# Generated by Django 4.2 on 2025-04-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='final_document',
            field=models.FileField(blank=True, null=True, upload_to='final_docs/'),
        ),
    ]
