# Generated by Django 4.2 on 2025-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0003_documentrequest_admin_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
