# Generated by Django 4.2 on 2025-04-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0004_documentrequest_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
