# Generated by Django 4.2 on 2025-05-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0005_documentrequest_address_documentrequest_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
