# Generated by Django 4.2 on 2025-05-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0006_documentrequest_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='family_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='ration_members',
            field=models.TextField(blank=True, null=True),
        ),
    ]
