# Generated by Django 4.2 on 2025-05-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0007_documentrequest_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='birth_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
